# Generated by Django 4.1.4 on 2022-12-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["title"],
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, verbose_name="Статья"),
        ),
        migrations.AlterField(
            model_name="article",
            name="photo",
            field=models.ImageField(null=True, upload_to="photos/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(blank=True, to="news.tag"),
        ),
    ]
