# Generated by Django 4.1.4 on 2023-01-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_category_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                max_length=30, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
