# Generated by Django 4.1.4 on 2023-01-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Статья"),
        ),
        migrations.AlterField(
            model_name="article",
            name="photo",
            field=models.ImageField(
                null=True, upload_to="photos/%Y/%m/%d", verbose_name="Фотография статьи"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="news.tag", verbose_name="Тэги"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Название статьи"),
        ),
    ]
