# Generated by Django 4.1.4 on 2023-01-05 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0006_article_favourites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="favourites",
        ),
        migrations.AddField(
            model_name="article",
            name="bookmarks",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarks_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="В закладках",
            ),
        ),
    ]
